### PR TITLE
Add Seeed XIAO ESP32C6 board definition

### PR DESCRIPTION
**Pull request by sigmdel**
## Description: 

Add Seeed XIAO ESP32C6 board definition

## Checklist:
  - [x] The pull request is done against the latest develop branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR, more changes are allowed when changing boards.json
  - [x] I accept the [CLA](https://github.com/pioarduino/platform-espressif32/blob/develop/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Jason2866** [comment]
thx

**Comment by Jason2866** [comment]
@sigmdel  Open boards PRs in repo Platformio have no impact here. If a new board is wanted to be seen in pioarduino a PR here needs to be made.

**Comment by alexbegoon** [comment]
@sigmdel any luck with BLE after?

**Comment by sigmdel** [comment]
@alexbegoon : Yes see, sketch `07_ble_led` in [https://github.com/sigmdel/xiao_esp32c6_sketches](sigmdel/xiao_esp32c6_sketches). There a bit more info in the associated [blog](https://sigmdel.ca/michel/ha/xiao/xiao_esp32c6_intro_en.html#ble) about testing using a smart phone app.

If you don't want to get the whole repo, just create an empty pio project, replace its `main.cpp` with [main.cpp](https://github.com/sigmdel/xiao_esp32c6_sketches/raw/refs/heads/main/07_ble_led/ble_led/main.cpp) and use this `platformio.ini`:

```ini
[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 460800
;upload_port = /dev/ttyACM0
;monitor_port = /dev/ttyACM0
```                                        
Good luck

**Comment by alexbegoon** [comment]
@sigmdel Thank you! 
@Jason2866 Great job! :people_hugging:

**Pull request merged**
