### PR TITLE
WaveShare ESP32-S3-Zero support

### PR DESCRIPTION
**Pull request by kdpuvvadi**
## Description:

**Related issue (if applicable):** fixes #<issue number goes here>

## Checklist:
  - [x] The pull request is done against the latest develop branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR, more changes are allowed when changing boards.json
  - [x] I accept the [CLA](https://github.com/pioarduino/platform-espressif32/blob/develop/CONTRIBUTING.md).

Anythings else needed, please let me know.

### CODE REVIEW

**Comment by sivar2311** [comment]
If I understand correctly, the board comes with 2 MB of quad SPI RAM.
So i am missing
```
    "extra_flags": [
      "-DBOARD_HAS_PSRAM"
```

**Comment by kdpuvvadi** [comment]
> If I understand correctly, the board comes with 2 MB of quad SPI RAM. 

It does, let me fix that.

**Comment by kdpuvvadi** [comment]
@sivar2311, am i missing anything else with this board?

**Comment by sivar2311** [comment]
@kdpuvvadi Unfortunately I don't have one, so I can't test it.

**Pull request merged**
